spring.application.name=fitnessstore

spring.datasource.url=jdbc:postgresql://ep-gentle-cake-apruk39q.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FWwArTf08hmu
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# THYMELEAF
spring.thymeleaf.cache=false

# SERVER
server.port=8080